apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-9-list-generator
  labels:
    app.kubernetes.io/name: example-9-list-generator
    app.kubernetes.io/part-of: argocd-applicationset-example
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        namespace: dev
  template:
    metadata:
      name: '{{cluster}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://github.com/choisungwook/argocd-applicationset.git
        targetRevision: HEAD
        path: example-3
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
