apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-b-nginx
  namespace: argocd
spec:
  project: cluster-b
  source:
    path: example-1
    repoURL: 'https://github.com/choisungwook/argocd-practice.git'
    targetRevision: HEAD
  destination:
    namespace: default
    server: 'https://cluster-b-control-plane:6443'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
