apiVersion: v1
kind: Pod
metadata:
  name: argocd-helloworld
  labels:
    name: argocd-helloworld
spec:
  containers:
  - name: argocd-helloworld
    image: nginx
    resources:
      limits:
        memory: "64Mi"
        cpu: "1"
    ports:
    - containerPort: 80
