apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            app: nginx
  template:
    metadata:
      name: "{{app}}-{{cluster}}"
      labels:
        app.kubernetes.io/managed-by: applicationset
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
      destination:
        server: "{{url}}"
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
